services:
  backoffice-backend:
    restart: always
    build: ./backend
    ports:
      - ${PORT:-5400}:${PORT:-5400}
    env_file:
      - backend/.env

  backoffice-frontend: 
    restart: always
    build: ./frontend
    ports:
      - 5500:5001
    env_file:
      - frontend/.env

